Repository nix-community/plasma-manager, pull requests merged in 2024-11, with the labels that each got.

#407 feat(session): init
  README.md
  modules/default.nix
  modules/session.nix
Labels: 0. type: enhancement, 4. has: plasma module (new)

#400 docs(treewide): typos, pass I
  docs/manual/introduction.md
  docs/manual/preface.md
  modules/apps/ghostwriter.nix
  modules/apps/kate/default.nix
  modules/apps/konsole.nix
  modules/apps/okular.nix
  modules/default.nix
  modules/desktop.nix
  modules/files.nix
  modules/fonts.nix
  modules/hotkeys.nix
  modules/input.nix
  modules/krunner.nix
  modules/kscreenlocker.nix
  modules/kwin.nix
  modules/panels.nix
  modules/powerdevil.nix
  modules/startup.nix
  modules/window-rules.nix
  modules/workspace.nix
Labels: 0. type: documentation

#391 feat(elisa): init Elisa module
  modules/apps/default.nix
  modules/apps/elisa.nix
Labels: 0. type: enhancement, 4. has: kde app module (new)

#410 Add explicit iconOnly option for the taskmanager
  modules/widgets/icon-tasks.nix
Labels: 0. type: enhancement, 5. first time contribution, 1. scope: widgets, 4. has: plasma widget module (update)

#427 feat(workspace): add wallpaperBackground option
  modules/apps/okular.nix
  modules/kwin.nix
  modules/widgets/icon-tasks.nix
  modules/widgets/plasmusic-toolbar.nix
  modules/workspace.nix
Labels: 0. type: enhancement, 1. scope: workspaces, 4. has: plasma module (update)
